github:
    repository_folder: ./models

dockerhub:
    username: mhubai
    
images:
    base_nocuda:
        name: base
        version: nocuda
        dockerfile: base/dockerfiles/nocuda/Dockerfile





