name: run run_automation.py

on:
  push:
    branches: [ "main" ]
  #schedule:
  #  - cron: '*/15 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 

      - name: checkout https://github.com/MHubAI/models
        uses: actions/checkout@v2 
        with:
          repository: MHubAI/models
          path: ./models

      - name: DockerHub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt

      - name: execute python script
        run: python ./src/github_automation.py --config "./config/github_actions/build_all.yaml"
